### ISSUE TITLE
Ktuvit stopped working

### ISSUE THREAD

**Issue by drtrotusk** [XBMCil/service.subtitles.subtitle#5]
Hi,

First, thanks for the addon! It is just great.
Unfortunately it stopped working lately. It shows "No Subtitles" when searching (for subtitles I already looked for) and when entering the right email and password it says that the credentials are wrong.
I suspect that it has something do to with the CAPTCHA that ktuvit added, but of course I'm not sure.

Tested it on OSMC (raspbian for RPI) and Linux Mint 17.2. Both running Kodi 16.1.

Will provide any needed information of course.

Thanks!

**Comment by CaTzil** [comment]
First of all without debug log, i can`t check what went wrong.
Can you check if you are able to login via desktop with CAPTCHA?
If not, they probably blocked your user.
if yes, so it probably related to the captcha thing...

Unfortunately, it not worth to work on work around of that, cause you have Subscenter & theWizSubs, that works flawlessly.

**Comment by drtrotusk** [comment]
Thanks for the prompt response and the recommendation for the other services.

Nevertheless, I can login through the web and here is the debug log: https://paste.ee/p/5zEob

**Comment by CaTzil** [comment]
Still relevant?
I`ve updated Ktuvit, and added an captcha request from the settings.

**Comment by drtrotusk** [comment]
Everything works great! Thanks!
